objects/Child_Obj__c.object
<CustomObject>
    <label>Child Obj</label>
    <nameField>
        <label>Child Obj Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Child Objs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Obj__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Obj</label>
        <referenceTo>Parent_Obj__c</referenceTo>
        <relationshipLabel>Child Objs</relationshipLabel>
        <relationshipName>Child_Objs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Parent_Obj__c.object
<CustomObject>
    <label>Parent Obj</label>
    <nameField>
        <label>Parent  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parent Objs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>No_of_Child_Actives__c</fullName>
        <label>No of Child Actives</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Child_Inactives__c</fullName>
        <label>No of Child Inactives</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/chidTriggerHandler.cls
public class chidTriggerHandler {
    public static void updateparentRecordNewChild(List<Child_Obj__c> childList){
        Set<Id> setParentIdsSet=new Set<Id>();
        Map<Id,decimal> activeMap=new Map<Id,decimal>();
        Map<Id,decimal> inactiveMap=new Map<Id,decimal>();
        List<Parent_Obj__c> parentList=new List<Parent_Obj__c>();
        decimal countOfActive=0;
        decimal countOfInactive=0;
        for(Child_Obj__c ch:childList){
            if(ch.Parent_Obj__c!=null){
                setParentIdsSet.add(ch.Parent_Obj__c);
            }
            if(ch.Status__c=='Active'){
                countOfActive=countOfActive+1;
            }else if(ch.Status__c=='Inactive'){
                countOfInactive=countOfInactive+1;
            }
            if(activeMap.containsKey(ch.Parent_Obj__c)){
                activeMap.put(ch.Parent_Obj__c,countOfActive);
            }else{
                activeMap.put(ch.Parent_Obj__c,countOfActive);
            }
             if(inactiveMap.containsKey(ch.Parent_Obj__c)){
                inactiveMap.put(ch.Parent_Obj__c,countOfInactive);
            }else{
                inactiveMap.put(ch.Parent_Obj__c,countOfInactive);
            }
        }
        System.debug('activeMap  '+activeMap);
        System.debug('inactiveMap  '+inactiveMap);
        parentList=[Select Id,No_of_Child_Actives__c,No_of_Child_Inactives__c from Parent_Obj__c WHERE Id IN:setParentIdsSet];
        System.debug('parentList  '+parentList);
        if(parentList!=null && !parentList.isEmpty()){
            for(Parent_Obj__c par:parentList){
                if(par.No_of_Child_Actives__c!=null){
                    par.No_of_Child_Actives__c=par.No_of_Child_Actives__c+activeMap.get(par.Id);
                }else{
                    par.No_of_Child_Actives__c=activeMap.get(par.Id);
                }
                if(par.No_of_Child_Inactives__c!=null){
                    par.No_of_Child_Inactives__c=par.No_of_Child_Inactives__c+inactiveMap.get(par.Id);
                }else{
                    par.No_of_Child_Inactives__c=inactiveMap.get(par.Id);
                }                
            }
            update parentList;
        }
    }
}