objects/LeaveRequest__c.object
<CustomObject>
    <description>Create A leave Request</description>
    <label>LeaveRequest</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LeaveRequest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>LeaveRequest</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>Reason</description>
        <label>Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <description>To Date</description>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <description>From Date</description>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Manager_Comment__c</fullName>
        <description>Manager Comment</description>
        <label>Manager Comment</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

classes/LeaveRequestController.cls
public with sharing class LeaveRequestController {
    @AuraEnabled(cacheable=true)
    public static List<LeaveRequest__c> getMyLeaves(){
        try{
            List<LeaveRequest__c> myLeavesList = new List<LeaveRequest__c>();
            myLeavesList=[SELECT Id,Name,From_Date__c,To_Date__c,Reason__c,Status__c,Manager_Comment__c from LeaveRequest__c Where User__c =:UserInfo.getUserId() ORDER BY CreatedDate DESC];
            return myLeavesList;
        }catch(Exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<LeaveRequest__c> getLeaveRequests(){
        try{
            Set<Id> userIdSet=new Set<Id>();
            List<LeaveRequest__c> myLeavesList = new List<LeaveRequest__c>();
            userIdSet.add(UserInfo.getUserId());
            myLeavesList=[SELECT Id,Name,From_Date__c,To_Date__c,Reason__c,Status__c,Manager_Comment__c,User__r.Name from LeaveRequest__c WHERE User__r.ManagerId IN:userIdSet ORDER BY CreatedDate DESC];
            return myLeavesList;
        }catch(Exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }
}